react-tags/react-tags

README.md
dist-modules/reactTags.js
lib/reactTags.js

PR for issue #18 
Added an optional prop (handleInputChange) for more flexibility regarding suggestions being passed in. This will allow for custom API requests to be made on the input's onChange, which will make suggestions more dynamic

Add handleInputChange event handler

---

package.json

Using the node_modules .bin is more future proof. If the babel project
were to rename or change their file structure the build script would
fail.
As a matter of fact they did this already.
`node_modules/babel/bin/index.js` has been renamed to `babel.js`

use node_modules/.bin/babel

---

README.md
dist-modules/reactTags.js
lib/reactTags.js

It's possible now to specify keys that, when pressed, apply current input. Previously those keys were hardcoded. Default behaviour does not change - enter and tab still terminate the input by default.
Now exporting ``Keys`` to allow library users to reuse some of react-tag-input codes.
Also added ``minQueryLength`` to README because it was missing (separate commit).

Allow to specify any keys as tag delimeters

---

lib/reactTags.js

It would crash if the input was an invalid regular expression, like 'aaa['. It would match everything if the input was '..' or '.*'. Now it's interpreting the input as a string.

bugfix: user input was interpreted as a regular expression

---

lib/reactTags.js

If I enter a non-suggested tag with autocomplete enabled the component creates an empty tag. This patch allows one to still add non-suggested tags with the benefit of autocompleting any suggestions.

Allow non-suggested tags to be used with autocomplete

---

lib/reactTags.js

Fixes issue #33
Set tag entry id as key for newly added tags (for example the tags is not saved in database, they don't have tag id)

Fix warning: Each child in an array or iterator should have a unique key

---

lib/tag.js

Changes the default remove component to use a proper cross (✕) symbol instead of the letter "x".

Use ✕ instead of x for default remove component

---

lib/reactTags.js

If `react-tags` catches the ESC key to close the suggestions menu it should not be allowed to propagate into the parent application.

stopPropagation of ESC key

---

lib/tag.js

If you notice [in your source code](https://github.com/prakhar1989/react-tags/blob/master/dist-modules/tag.js#L92), the close button &mdash; despite being represented in its HTML entity form in your source code &mdash; is rendered as an actual &times; in the `dist-modules`. This causes problems in certain encoding environments.
I've changed the HTML entity to using `String.fromCharCode` which should eliminate this problem 👍 
There's no reason why this change should cause any issues, and so I think a simple patch update should do the trick.

Using fromCharCode instead of HTML entity for representing close

---

lib/ReactTags.js
lib/Suggestions.js
test/reactTags-test.js

Sorry &mdash; a little oversight!
I think once we've invoked the `handleInputBlur` function, the `input` should be cleared, as the assumption is that the text was added as a tag.
Alternatively we could clear the input based on the return value of the `handleInputBlur` function, but that seems like it could cause confusion, although it would offer the developer greater control.

Clearing input once invoked onBlur handler

---

lib/ReactTags.js

In [the example](http://prakhar.me/react-tags/example/) holding down <kbd>shift</kbd> whilst pressing <kdb>enter</kbd> adds the tag, when in reality that key combination is technically different from just <kbd>enter</kbd>.
For the above example it doesn't matter too much, but when you set your `delimiter` to <kbd>tab</kbd> for instance, then you're unable to enter <kbd><</kbd> into the textbox because the `keyCode` for <kbd>,</kbd> is the same as <kbd><</kbd> and thus takes it as the `delimiter`.
This change ensures the <kdb>shift</kbd> isn't being held down. Interestingly I couldn't find any tests for `addTag` and so I didn't add a test for this PR. Existing tests pass just fine.
I don't imagine this change will affect anybody as it really is an edge-case, however it is a breaking …

Asserting that the shift key isn't being held down

---

lib/ReactTags.js
test/reactTags-test.js

`react-tags` allows developers to specify the delimiters, but when it comes to `handlePaste` it disregards those delimiters and uses `\s,` which is undesirable because your pasted content *may* allow spaces and commas in its content, depending on your chosen delimiter(s).
~~There doesn't seem to be any tests relating to `handlePaste` so I haven't added one at this stage.~~

Using passed delimiters to split pasted content

---

README.md
example/reactTags.css
lib/ReactTags.js
test/reactTags-test.js

In regards to issue #32 , adds the ability to pass in a custom className for the `<input>` element, rather than just the outer `<div>`.

Add the ability to pass in a custom className for the <input> element

---

lib/Suggestions.js
lib/Tag.js
package.json

Hi there!
I'm using your sweet library for a project and ran into some performance issues with the suggestions list. The main issue is that my parent component is rendering rapidly, which causes the `Suggestions` component to render again. Since the suggestions never actually changed, this is a bit of a waste.
My changes add a simple `shouldComponentUpdate` to the `Suggestions` component to prevent needless renders and improve performance.

Prevent suggestions from rendering unless the values have changed

---

lib/ReactTags.js

Step to reproduce:
- Run the `npm run dev` example with `autocomplete={true}` props
- Type `Ind` and navigate in the suggestions without validate
- Type additional characters to have no suggestions, ie `Indy`
- Press enter
- The new tag is not added
=> `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`

Fix adding a new tag in SelectionMode

---

lib/Suggestions.js
lib/Tag.js

This cuts the bundle size by more than half.
Before:
```
rkm@hanekawa ~/Documents/git/react-tags (git)-[v4.6.1] % npm run build
> react-tag-input@4.6.1 build /Users/rkm/Documents/git/react-tags
> webpack -p && babel lib --out-dir dist-modules
Hash: 6327f95bd25ea655d754
Version: webpack 1.14.0
Time: 5478ms
Asset    Size  Chunks             Chunk Names
ReactTags.min.js  115 kB       0  [emitted]  main
+ 116 hidden modules
WARNING in ReactTags.min.js from UglifyJs
Condition always true [./~/lodash/lodash.js:17041,0]
Dropping unreachable code [./~/lodash/lodash.js:17055,0]
lib/ReactTags.js -> dist-modules/ReactTags.js
lib/Suggestions.js -> dist-modules/Suggestions.js
lib/Tag.js -> dist-modules/Tag.js
```
After:
```
rkm@hanekawa ~/Documents/git/react-tags (git)-[master] % npm run build
> …
```

Don't import all of `lodash`

---

lib/Suggestions.js
test/suggestions.test.js

Suggestions don't always render when they're supposed to (e.g. hitting `minQueryLength` is not sufficient, always have to hit `minQueryLength+1` for a render to occur). Looking at the implementation of `shouldComponentUpdate` and `shouldRenderSuggestions` suggests two issues
1. `shouldComponentUpdate` is ignoring nextProps
2. `shouldRenderSuggestions` is ignoring the `query` argument

fix re-rendering of Suggestion to make use of nextProps

---

lib/ReactTags.js

Fixes https://github.com/prakhar1989/react-tags/issues/165
Before bug, that can be replicated by setting `autofocus={false}` on the example.
The bug came from https://github.com/prakhar1989/react-tags/commit/4429be7922173e25a764fb26ced8898a15e49edf?diff=split#diff-833c370f0b7e67628628a041d1984df3L211 , where after tag addition the input would only reset if autofocus wasn't false. I decided to move the if condition into only `componentDidMountt`, as I am under the assumption that the input should be focused after tag deletion regardless of the autofocus prop. 
I didn't see a way to add in a test to ensure the input gets cleared after adding a tag, but if that is possible please point me in the right direction!

Fix reset input when autofocus=false

---

package.json

This reverts commit c16490cc7eb20feff808e7112ece66199a5d3536, since it's only needed when building and fails unnecessarily when installed as a dependency in `node@4` (e.g., via `react-tag-input`).

Revert "chore(package.json): "require" node 5+ to build"

---

lib/ReactTags.js
lib/Suggestions.js
package.json
test/reactTags.test.js
test/setupTest.js
test/suggestions.test.js
test/tag.test.js

Update to react 16
* `inputValue` props is necessary because setting the input field value throws `TypeError: Can't add property value, object is not extensible` see the test that was split into 2

Update to use react 16

---

lib/Tag.js
test/tag.test.js

Passing current tag object to removeComponent allow us to conditionally render remove component. This will help us to decide which tag is removable and which not without using readOnly prop do disable them all.

Pass current tag object to removeComponent for conditional rendering

---

lib/ReactTags.js

If a tag doesn't have an id field, it would throw a duplicate key warning.
If a tag has an id prop, use that, if not, use the map index as a key.

Fix for duplicate key prop if tag has no id

---

lib/ReactTags.js
lib/Suggestions.js
test/reactTags.test.js
test/suggestions.test.js

Updated code so minQueryLength can be set to 0 in order to show suggestions when input is focused and allow keyboard selection when minQueryLength is set to 0.
Issue #36

Issue 36 - Showing all items + Keyboard selection when minQueryLength=0 

---

README.md

I think the example included in the repo is hard to maintain and doesn't quite show the actual usage of the library, so adding a stackblitz demo which users can fork and play right in the browser might be a nice way to experiment.
Here's the demo: https://react-tag-input.stackblitz.io

Add stackblitz for demoing library usage

---

lib/ReactTags.js
test/reactTags.test.js

When `readOnly` is `true`, both `handleAddtion` and `handleDelete` are unused. Provide a noop function as a default prop and remove the requirement for them to be provided.
Fixes #303

Give handleAddition and handleDelete default props

---

lib/ReactTags.js

Per request from @ad1992 on #304, moving the prop types and default props into the `ReactTags` class and making them static members.

Move the props and default props into the class

---

lib/ReactTags.js
lib/utils.js
package.json
test/reactTags.test.js

* By being explicit about what functions we want from lodash, we can reduce the bundle size by ~50%.
* Adding 'sideEffects: false' to package.json to allow webpack4 optimize re-exports (https://github.com/webpack/webpack/tree/master/examples/side-effects).
Before:
* ReactTags.min.js 143 kB
After:
* ReactTags.min.js 72.4 kB

Import only wanted parts of lodash

---

package-lock.json
package.json
webpack-dev-server.config.js
webpack-production.config.js

* also upgraded webpack-dev-server and babel-loader and the cli tools are split out to webpack-cli, so installed that.
* updated configuration for new syntax. UglifyJS is now replaced by optimization.minimize flag.
* added 'sideEffects: false' to package.json so webpack can optimize re-exports.

Upgrade webpack to v4.11.1

---

lib/ReactTags.js
test/reactTags.test.js

The `tag` object was sent to `filteredSuggestions`, but the actual text was expected. Sending `tag.text` fixes the issue. Closes #342

fix autocomplete bug

---

lib/ReactTags.js

While implementing the library i noticed that maxLength requires a number as a prop but in ReactTags.js a string is required.

Change propTypes for maxLength

---

README.md
__tests__/suggestions.test.js
src/components/ReactTags.js
src/components/Suggestions.js

This feature allows to pass a default functional component as a prop and override default suggestion component. I wrote it because I need it for my own project, in order to show different icons based on the type of suggestion. I would be glad if you reviewed it and considered adding this feature to your library so that anyone can use it. I would also be glad to receive some feedback, as I have no experience contributing to open source libraries.
Thanks!

feat: Add custom suggestion as a prop

---

src/components/ReactTags.js

When there are no tags left and the user tries to delete tags, we get this error for the line, because the value of `currentTags[index]` will be `undefined`
https://github.com/prakhar1989/react-tags/blob/19faa054bf33e9d355e8f31e7558ccd92c981056/src/components/ReactTags.js#L167
I have added any early return from the `handleDelete` function to avoid this error

fix(ReactTags): Fix delete error when tags are empty

---

README.md
__tests__/__snapshots__/reactTags.test.js.snap
__tests__/reactTags.test.js
example/main.js
src/components/ReactTags.js
src/components/RemoveComponent.js
src/components/constants.js

fixes #721 
Fixes problem with pasting multiline text. 
Based on the https://github.com/react-tags/react-tags/blob/master/src/components/constants.js#L2 , enter delimiter is marked as unicode `13` (Carriage return), which is partially true. Enter should be also marked with unicode `10` (Line feed). Please see https://stackoverflow.com/a/1761064
That means on windows/edge it works in partial - it splits a text by `\r`:  `word1\r\nword2` -> `['word1', '\nword2']` but in other systems it does not split text at all.
Tested on Chrome, Safari, Edge, Firefox

fix: redefine new line delimiter

---

__tests__/RemoveComponent.test.js
__tests__/__snapshots__/RemoveComponent.test.js.snap
jest.config.js
package.json
src/components/RemoveComponent.js
yarn.lock

I wish to use ReactTags inside a form
To prevent tag's removing when I press on Enter (to submit the form), I do need to set a type to all my buttons.
ReactTags did not set any type to this RemoveComponent's button. So I added it.

fix: Add type to remove button

---

.travis.yml

fix the breaking build in [6.7.2](https://app.travis-ci.com/github/react-tags/react-tags/builds/232481517)

fix: use yarn install instead of npm

---

src/components/Tag.js

this fixes #795 
removed `onKeyDown` prop passed `RemoveComponent` component as it doesn't have this prop registered and i believe this was added by mistake (with onKeyDown being undefined)
also the `onKeyDown` is already handled inside the `RemoveComponent` component

fix: remove undefined onkeydown prop passed to RemoveComponent

---

package.json

The globs used in the `format` script are incorrect for nested files and is logging a "No files matching the pattern were found" error

chore: change globs in npm format script

---

package.json
yarn.lock

Allow React 18 to be used as a peer dependency. Fixes https://github.com/react-tags/react-tags/issues/855

chore: Update React to ^18.2.0 in  peerDependencies

---

src/components/Suggestions.js

The suggestion `scrollTop` feature isn't working because the `querySelector` API requires a selector prefix for classes (`.`).
This was originally implemented in https://github.com/react-tags/react-tags/pull/93.

fix: add missing required class selector prefix for scrolling active suggestion

---

README.md
__tests__/ReactTags.test.tsx
__tests__/__snapshots__/ReactTags.test.tsx.snap
example/main.js
src/components/ReactTags.tsx

Deleting tags via backspace is needed and expected behaviour only when input position is inline. For `top/bottom` positions, the behaviour is confusing and looks buggy as well. Hence I am only keeping this behavior when the input field is `inline`.
For now I am keeping the prop but, I feel that we don't need this prop as I don't see the use cases where people would like to have this behavior for top/bottom input field positions. I will open an issue regarding this so we can discuss it there

fix: delete tag when backspace is pressed only when input field position is inline

---

package.json

Make default export last in package.json.
Certain build tools (microbundle) require the default export to be last in the exports object.  See e.g. https://stackoverflow.com/questions/76127288/module-not-found-error-default-condition-should-be-last-one.

build: Change export order

---

webpack-dev-server.config.cjs

For building the library we have moved to `esbuild` but dev server still uses `webpack` so should switch to `esbuild` completely soon or `vite`
Since webpack doesn't support importing files for module type packages (ESM) hence the field `resolve.fullySpecified` needs to be set to false to make the imports work, more info [here](https://webpack.js.org/configuration/module/#resolvefullyspecified)
closes https://github.com/ad1992/fuzzify/issues/15

build: set resolve.fullySpecified to false so mjs/js imports without specifying extensions for ESM in webpack dev server

---

example/main.tsx
example/public/index.html

CSS was not being loaded since https://github.com/react-tags/react-tags/pull/971/files
closes #991

fix: load bundle.css so preview build works

---

src/index.tsx

The className property as an object was optional but when the className is provided it was required to provide all the properties declared or needed in className. 
From chatGPT the more explanation 
```
classNames?: {
tags: string,
tagInput: string,
tagInputField: string,
selected: string,
tag: string,
remove: string,
suggestions: string,
activeSuggestion: string,
editTagInput: string,
editTagInputField: string,
clearAll: string,
}
```
The ? here means that classNames itself is optional. You can choose to provide or omit this property.
Each property inside the classNames object is required if the classNames object is provided. You must include all these properties with corresponding string values if you use the classNames object.
```
classNames?: {
tags?: string,
tagInput?: string, …
```

fix: type issue in classNames prop

---

__tests__/ReactTags.test.tsx
src/components/ReactTags.tsx

>[!NOTE]
> The solution needs to be tested by a proper Korean language user. Being a non-Korean language user, I can change the keyboard type and type input and test, but I will not be able to say whether what I tested is proper according to the Korean language, 
Korean and Japanese languages characters are formed using the compositions of keys. 
From GPT:
Composition-based Input:
Korean, like many East Asian languages, often uses an Input Method Editor (IME) for text entry. This involves a composition process where multiple keystrokes may be required to form a single character.
Challenges:
1. The value of the input field may not be final until the composition is complete.
2. Key events may fire multiple times for a single Korean character.
3. The keyCode or which properties may not …

fix: Korean input trigger keydown event twice

---

README.md
__tests__/ReactTags.test.tsx
src/components/ClearAllTags.tsx
src/components/ReactTags.tsx
src/index.tsx

**Issue:** Clear all buttons don’t explain what to clear. it feels like I am trying to clear texts in input but actually, it does clear tags
**solution** : Give a prop to provide an alt tag to clear all CTA in case CTA is provided. If not give the default alt tag as “clear all chosen tags”
accessibility tree
| then | now |
|--|--|
|<img width="1015" alt="Screenshot 2024-10-01 at 8 19 04 PM" src="https://github.com/user-attachments/assets/dfefd9df-e9a2-45f6-9760-367c135c5e1b"> | <img width="1053" alt="image" src="https://github.com/user-attachments/assets/b3064825-1eb5-4770-a1cb-c24e7178141a">|
screen reader announcement when clear all CTA is being focused 
This fixes first issue in https://github.com/react-tags/react-tags/issues/999

fix: accessibility issue in clear all cta

---

src/index.tsx

This PR adds the export of the `Tag` type to the index file to allow users to import it via `import { Tag } from "react-tag-input";`

fix(exports): properly export tag type
