lib/reactTags.js

add placeholder prop option

---

lib/Tag.js
lib/reactTags.js

add labelField option for the property name of `tags collection` to render as an option / item label (default to `text`

add labelField prop option

---

README.md
lib/ReactTags.js
test/reactTags-test.js

Initial concept for https://github.com/prakhar1989/react-tags/issues/84

Added support for onBlur event handling

---

lib/ReactTags.js
test/reactTags-test.js

Invoking handleInputBlur irrespective of input value

---

lib/Suggestions.js
test/suggestions-test.js

Fixes a bug introduced by PR #123.

Allow suggestions to re-render while interacting with the component.

---

README.md
lib/ReactTags.js

I'm using your lib in a project and it would be nice to have those attributes on the input field. 
See in #107

Add name, id and maxLength props to input field

---

README.md

Add ES2015+ style to docs

---

lib/ReactTags.js
lib/Tag.js

Following [this example](https://react-dnd.github.io/react-dnd/examples-sortable-simple.html) ([source](https://github.com/react-dnd/react-dnd/tree/master/examples/04%20Sortable/Simple)) I made the drag n drop smoother

Make drag n drop smoother

---

README.md
example/main.js
lib/ReactTags.js
lib/Tag.js
test/tag.test.js

Tags element supports handling a click event on a certain tag.
(This is needed in order to be able to identify which tag was clicked)

Added ability to handle a click event on a certain tag

---

lib/ReactTags.js
lib/Suggestions.js
lib/Tag.js
test/reactTags.test.js

@mrdannael @prakhar1989  please look into this.

fix #235, don't allow duplicate tags

---

README.md

update stackblitz link

---

example/main.js

update example code

---

.eslintrc.js
lib/DragAndDropHelper.js
lib/RemoveComponent.js
lib/Tag.js
test/tag.test.js

Will fix the `findDOMNode` in next PR.
cc @prakhar1989 @mrdannael

split the components in Tag.js into different files and cleanup

---

.eslintrc.js
.hooks/pre-commit
package-lock.json
package.json
test/reactTags.test.js

fixes in https://github.com/prakhar1989/react-tags/pull/322

Cdreve precommit hook

---

.eslintrc.js
package-lock.json
package.json

update eslint-plugin-react and add babel-eslint

update eslint-plugin-react and add babel-eslint

---

lib/ReactTags.js
package-lock.json

Fix: Don't trim value when passing to handleChange prop

---

.codeclimate.yml
README.md
src/ReactTags.js
test/reactTags.test.js

fixes https://github.com/prakhar1989/react-tags/issues/258

Add allowUnique prop

---

example/main.js
src/components/ReactTags.js
src/components/Suggestions.js

* Move code from componentWillMount to constructor.
* Remove code from componentWillReceiveProps.
* fixes #417

Fix(ReactTags): Remove UNSAFE component lifecycles

---

README.md

Since @ad1992 is doing such a stellar job! 🎉

Remove the call for more contributors. Fix #197

---

__tests__/reactTags.test.js
src/components/ReactTags.js

Add Partial word search according with issue #352 
Note: at all suggestions list first displayed suggestions with first match characters, after that displayed suggestions with partial match

Add partial word search

---

__tests__/reactTags.test.js
__tests__/suggestions.test.js
package-lock.json
package.json
src/components/ReactTags.js

The bots forced me to add a small refactoring to make the code climate green again.

fix: Fix #508 (Changing the suggestions prop doesn't trigger an update)

---

src/components/ReactTags.js
src/components/Tag.js

Resurrected from another PR
Hopefully fixes issue #559
I commented on [this PR](https://github.com/prakhar1989/react-tags/pull/583/files) and the author quickly closed it
I will reiterate the same points I stated over on that one, and test it out to see if it fixes the issue

fix(ReactTags): Drag and drop failing

---

package-lock.json
package.json

Remove core-js from dependencies

---

__tests__/tag.test.js
example/index.html
example/reactTags.css
package-lock.json
src/components/ReactTags.js
src/components/RemoveComponent.js
src/components/Tag.js

Remove unncessary css files from example
Remove `onKeydown` event from Tag as it wasn't getting used since tags aren't tabbable yet
fixes https://github.com/prakhar1989/react-tags/issues/675

fix: change cross icon to button so its tabbable

---

__tests__/reactTags.test.js
src/components/ReactTags.js
src/components/RemoveComponent.js
src/components/Tag.js
src/components/constants.js
webpack-dev-server.config.js

* Focus to the previous tag when deleted and also annouce to sr
* Only allow backspace to remove tags

feat: Allow backspace to remove tags when focussed on cross button.

---

README.md
__tests__/__snapshots__/reactTags.test.js.snap
__tests__/reactTags.test.js
__tests__/setupTest.js
src/components/ReactTags.js

fixes https://github.com/react-tags/react-tags/issues/695, https://github.com/react-tags/react-tags/issues/461

feat: Add support for inputProps

---

README.md
__tests__/tag.test.js
src/components/RemoveComponent.js

fixes https://github.com/react-tags/react-tags/issues/707

fix: pass relevant props to custom remove component and fix docs

---

__tests__/reactTags.test.js
src/components/ReactTags.js
src/components/constants.js

fixes https://github.com/react-tags/react-tags/issues/728

fix: Don't show suggestions which are already added when allowUnique is true

---

README.md

fixes https://github.com/react-tags/react-tags/issues/665

docs: add allowAdditionFromPaste prop in readme

---

README.md
example/main.js

fixes https://github.com/react-tags/react-tags/issues/769

docs: update docs to use hooks

---

.github/workflows/Semnatic-PR.yml

Added Semnatic PR github action

build: add Semnatic-PR.yml gh action

---

__tests__/__snapshots__/reactTags.test.js.snap
__tests__/reactTags.test.js
example/main.js
example/public/reactTags.css
src/components/ReactTags.js
src/components/constants.js

This PR adds support for max number of tags through maxTags (optional) prop, reference issue #920

feat: Add support for max number of tags allowed

---

__tests__/__snapshots__/reactTags.test.js.snap
__tests__/reactTags.test.js
example/main.js
src/components/ReactTags.js

closes https://github.com/react-tags/react-tags/issues/930

fix: trim the tags before adding

---

README.md
__tests__/ReactTags.test.tsx
__tests__/__snapshots__/ReactTags.test.tsx.snap
src/index.tsx

Details found in atttached issue:
- #979

fix(classNames): update the className attributes so its correctly typed and passed to the DOM

---

README.md

Fixing a 404 - thanks for the fantastic package!

docs: broken link css -> scss.
